version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test  # Base de datos de producción
      POSTGRES_USER: postgres  # Usuario de la base de datos
      POSTGRES_PASSWORD: postgres  # Contraseña de la base de datos
    ports:
      - "5433:5432"  # Puerto local para la base de datos

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # Aquí es donde se configura la base de datos según el entorno
      - DATABASE_SELECTED=${DATABASE_SELECTED}
      
      # Variables para la base de datos (dependiendo de si es de producción o prueba)
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      
      # Dependiendo de DATABASE_SELECTED, usa la base de datos de prueba o producción
      - DATABASE_HOST=${DATABASE_HOST}  # En producción: junction.proxy.rlwy.net
      - LOCAL_DATABASE_NAME=${LOCAL_DATABASE_NAME}
      - LOCAL_DATABASE_USER=${LOCAL_DATABASE_USER}
      - LOCAL_DATABASE_PASSWORD=${LOCAL_DATABASE_PASSWORD}
      - LOCAL_DATABASE_HOST=db  # Solo se usa para pruebas locales
      - LOCAL_DATABASE_PORT=${LOCAL_DATABASE_PORT}  # Solo se usa para pruebas locales

      # Variables para Cloudinary
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}  
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_SECURE=true
      - CLOUDINARY_STORAGE=cloudinary_storage.storage.MediaCloudinaryStorage

      #variables para paypal
      - PAYPAL_RECEIVER_EMAIL=${PAYPAL_RECEIVER_EMAIL}

      # Variables para el envío de correos
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}

volumes:
  postgres_data:
