# Generated by Django 5.1.2 on 2024-11-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_quantity_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=5)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'currencies',
            },
        ),
    ]
