# Generated by Django 5.1.2 on 2024-12-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_formatted',
            field=models.CharField(default='', max_length=255),
        ),
    ]
